### ISSUE TITLE
Python 2 or Python 3?

### ISSUE THREAD

**Issue by whaleygeek** [MakeTronix/Examples#1]
Are you going to support Python 2 or Python 3 with this code? I think it would be useful to either state which version of Python you are using, and/or support both versions. Also give an example as to how to run the programs (as that will influence which version of python is actually loaded)

Your hash-bang line runs with python (which defaults to python 2)

https://github.com/MakeTronix/Examples/blob/master/alarm_test.py#L1

But your import uses _thread, which is a python 3 version of the low level threading API

https://github.com/MakeTronix/Examples/blob/master/alarm_test.py#L7

See below terminal trace:

Davids-MacBook-Air-2:~ davidw$ python
Python 2.7.6 (v2.7.6:3a1db0d2747e, Nov 10 2013, 00:42:54) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _thread
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named _thread
>>> quit()

Davids-MacBook-Air-2:~ davidw$ 
Davids-MacBook-Air-2:~ davidw$ python3
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _thread
>>> quit()
Davids-MacBook-Air-2:~ davidw$

**Comment by ZacharyIgielman** [comment]
We're using python3, it should all work with that

**Comment by whaleygeek** [comment]
Ok, are you sure about that? The hash bang line implies python2, and _thread (with the underscore) fails to import on Python 3 - see above trace.

**Comment by ZacharyIgielman** [comment]
It works on python3, no?

I will ammend the hash bang line

**Comment by ZacharyIgielman** [comment]
is it correct now?

**Comment by whaleygeek** [comment]
That should work. Although you might find the /usr/bin/env utility more flexible if you ever port to other platforms.

http://stackoverflow.com/questions/2429511/why-do-people-write-usr-bin-env-python-on-the-first-line-of-a-python-script
