### ISSUE TITLE
Use of sys.exit

### ISSUE THREAD

**Issue by whaleygeek** [MakeTronix/Examples#2]
sys.exit() is usually considered a rather unsafe way to stop a program as it might not completely release all system resources cleanly.

It looks like you have used this, because you haven't stopped your thread you started earlier, and this will force Python to keep your app running until all threads stop (which it never does).

One way that you can safely stop a thread that is repeatedly looping, is to have a flag 'running' that you set to false when you call your stop() method, this sets the 'running' flag to false, and the 'while' loop in your run() method then safely terminates.

http://stackoverflow.com/questions/15729498/how-to-start-and-stop-thread

You can then just call your stop() method at the end of your program (not needing sys.exit), the flag will set, the run() method will terminate, then all threads have stopped so the main program will safely exit.

**Comment by ZacharyIgielman** [comment]
I've made some changes to the alarm file to what I think you mean, can you check?

**Comment by whaleygeek** [comment]
Yes, that looks better. Well done.

You should generally avoid sys.exit() if at all possible. It's usually best to only use for error handling, rather than normal program exit.
